name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
permissions:
  contents: write
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Fetch latest data
      run: |-
        curl -s https://apps.odense.dk/data/newtags/115-dk-light.json | jq '.' > 115-dk-light.json
    - name: Commit and push if it changed
      run: |-
         git config user.name github-actions
         git config user.email 41898282+github-actions[bot]@users.noreply.github.com
         git add -A
         timestamp=$(date -u)
         git commit -m "Opdateret: ${timestamp}" || exit 0
         git push
